# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16oIluUAq8iKGv0kb0I4AthP-AydIlxp3
"""

import pandas as pd
baza={
    "F.I.SH.":["Aliyev Vali","Axror Qayumov","Laziza Rahimova","Javohir Bahodirov","Ismoilov Xondamir","Akramov Jasur","G'ulomova Farzona","SHamsiddinov Sherzodbek","Abdullayev Abror","Doltaboyev Muhammadjon"],
    "yoshi":["12","40","18","19","19","19","19","18","19","19"],
    "maktabi":["6-maktab","?-maktab","6-maktab","6-maktab","6-maktab","6-maktab","6-maktab","6-maktab","6-maktab","6-maktab"],
    "jinsi":["o'g'il bola","o'g'il bola","qiz bola","o'g'il bola","o'g'il bola","o'g'il bola","qiz bola","o'g'il bola","o'g'il bola","o'g'il bola"],
    "manzili":["Farg'ona shahar ","Farg'ona shahar ","Farg'ona shahar ","Farg'ona shahar","Qoqon shahar","Toshkent shahar ","Farg'ona shahar","Toshkent shahar","Farg'ona shahar ","Farg'ona shahar "],
}
db=pd.DataFrame(baza)
print(db)

filtr=db[db['jinsi']=="qiz bola"]
print(filtr)

filtr=db[db['jinsi']=="o'g'il bola"]
print(filtr)

filtr=db[db['yoshi']=="19"]
print(filtr)

filtr=db[(db['yoshi']=="19") &(db['jinsi']=="qiz bola")]
print(filtr)

filtr=db[(db['yoshi']=="18") &(db['jinsi']=="qiz bola")]
print(filtr)